// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ViGlideAdaptix_DAL.Models;

public partial class PaymentHistory
{
    public int PaymentHistoryId { get; set; }

    public int OrderId { get; set; }

    public int CustomerId { get; set; }

    public decimal TotalPrice { get; set; }

    public int PaymentMethodId { get; set; }

    public DateTime PaymentDate { get; set; }

    public virtual Order Order { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }
}